
# -------------------------------------------------------------------
# Copyright (c) 2018 Denys Bortovets
# This file is part of the extensive testing project
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA
# -------------------------------------------------------------------


"""
This is a setup.py script generated by py2applet

For building mac app run app-client/Scripts/qt5/MakeMacAppDMG.sh

"""

from setuptools import setup
from Main import __VERSION__

APP = ['../../Main.py']
APP_NAME = "ExtensiveTestingClient_%s" % __VERSION__
DATA_FILES = ['../../Files']


OPTIONS = {
    'argv_emulation': True,
    'iconfile': '../../Resources/ExtensiveTestingClient2.icns',
    'includes': ['sip', 'PyQt5', 'QScintilla'],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "ET Client",
        'CFBundleVersion': "%s" % __VERSION__,
        'CFBundleShortVersionString': "%s" % __VERSION__,
        'NSHumanReadableCopyright': u"Copyright © 2018, Denys Bortovets, All Rights Reserved"
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
